services:
  # Frontend
  - type: web
    name: ims-frontend
    env: static
    plan: free
    buildCommand: "npm run build"
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://ims-backend.onrender.com/api
